SfdEnerji.web/Areas/Admin/Controllers/ContactFormController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SfdEnerji.Models;
using SfdEnerji.Models.DTOs;
using SfdEnerji.Repository.Shared.Abstract;

namespace SfdEnerji.web.Areas.Admin.Controllers
{
    public class ContactFormController : ControllerBase
    {
        public ContactFormController(IUnitOfWork unitOfWork):base(unitOfWork) 
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Add(ContactForm contactForm)
        {
            unitOfWork.ContactForms.Add(contactForm);
            unitOfWork.Save();

            return View();
        }

        public IActionResult GetAll()
        {
            return Json(new
            {
                data = unitOfWork.ContactForms.GetAll().Select(cf => new ContactFormDto
                {
                    Id = cf.Id,
                    Name = cf.Name,
                    Message = cf.Message.Substring(0, 100),
                    CreatedDate = cf.CreatedDate,
                    MessageLenght = cf.Message.Length,
                    Email = cf.Email,
                    Subject = cf.Subject



                }).ToList()
            });
        }

        [HttpPost]
        public IActionResult DeleteById(int contactFormId)
        {
            unitOfWork.ContactForms.DeleteById(contactFormId);
            unitOfWork.Save();
            return Ok("Başarıyla silindi");
        }

        [HttpPost]
        public IActionResult Update(ContactForm contactForm)
        {
            unitOfWork.ContactForms.Update(contactForm);
            unitOfWork.Save();
            return Ok();
        }
        [HttpPost]
        public string ReadMessage(int contactFormId)
        {
            return unitOfWork.ContactForms.GetById(contactFormId).Message;
        }

    }
}

SfdEnerji.web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using SfdEnerji.Repository.Shared.Abstract;

namespace SfdEnerji.web.Areas.Admin.Controllers
{
    public class DashboardController : ControllerBase
    {
        public DashboardController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {

        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

SfdEnerji.web/Areas/Admin/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using SfdEnerji.Models;
using Microsoft.EntityFrameworkCore;
using SfdEnerji.Repository.Shared.Abstract;
using SfdEnerji.Utility;
using SfdEnerji.Repository.Shared.Concrete;

namespace SfdEnerji.web.Areas.Admin.Controllers
{
    public class ServiceController : ControllerBase
    {
        public ServiceController(IUnitOfWork unitOfWork) : base(unitOfWork)
        {

        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            return Json(new { data = unitOfWork.Services.GetAll().Include(s => s.Pictures).ToList() });
        }

        [HttpPost]
        public IActionResult Add([FromForm] Service service)
        {
            //var deneme = Request.Form["slug"];
            var deneme = service.slug;

            var thumbnail = Request.Form.Files["file"];
            var Extencion = Path.GetExtension(thumbnail.FileName);
            string dosyAdi = service.slug.TextClean() + "_" + Helper.RandomStringGenerator(5) + "_" + "-Hizmet" + Extencion;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Files", "Services");


            if (thumbnail != null && thumbnail.Length > 0)
            {
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                var stream = new FileStream(Path.Combine(path, dosyAdi), FileMode.Create);
                thumbnail.CopyToAsync(stream);
                service.Thumbnail = dosyAdi;

            }
            service.CreatedDate = DateTime.Now;
            service.ModifitedDate = DateTime.Now;
            unitOfWork.Services.Add(service);

            unitOfWork.Save();
            return Ok();

        }

        public IActionResult Pictures(int serviceId)
        {

            return View(unitOfWork.Services.GetAll(x => x.Id == serviceId).Include(s => s.Pictures).FirstOrDefault().Pictures.Where(p => p.IsDeleted == false).ToList());
        }

        public IActionResult PicturesAjax()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetAllPictures(int serviceId)
        {
            return Json(unitOfWork.Services.GetAll(x => x.Id == serviceId).Include(s => s.Pictures).FirstOrDefault().Pictures.Where(p => p.IsDeleted == false).ToList());
        }

        [HttpPost]
        public IActionResult SavePictures(List<IFormFile> postedFiles, int serviceId)
        {

            Service service = unitOfWork.Services.GetById(serviceId);

            foreach (var file in postedFiles)
            {
                var fileName = service.Name.TextClean() + "-" + Helper.RandomStringGenerator(10) + "-" + file.FileName.TextClean();
                var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Files", "Services", "Gallery");

                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                //dosyayi diske kaydetme kısmı
                var stream = new FileStream(path + "/" + fileName, FileMode.Create);
                file.CopyToAsync(stream);
                stream.Close();
                Picture picture = new Picture();
                picture.Path = fileName;
                picture.Description = "";
                picture.Name = service.slug;
                service.Pictures.Add(picture);


            }
            service.ModifitedDate= DateTime.Now;
            unitOfWork.Services.Update(service);
            unitOfWork.Save();

            return RedirectToAction("Pictures", serviceId);
        }

        public IActionResult DeletePicture(int pictureId, int serviceId)
        {

            unitOfWork.Pictures.DeleteById(pictureId);
            unitOfWork.Save();
            return RedirectToAction("Pictures", new { serviceId = serviceId });

        }

        public IActionResult DeletePictureAjax(int pictureId)
        {

            unitOfWork.Pictures.DeleteById(pictureId);
            unitOfWork.Save();
            return Ok();

        }

    }
}

SfdEnerji.web/Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8" />
    <title>Chat | Minible - Admin & Dashboard Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
    <meta content="Themesbrand" name="author" />
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.ico">

    <!-- Bootstrap Css -->
    <link href="~/assets/css/bootstrap.min.css" id="bootstrap-style" rel="stylesheet" type="text/css" />
    <!-- Icons Css -->
    <link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
    <!-- App Css-->
    <link href="~/assets/css/app.min.css" id="app-style" rel="stylesheet" type="text/css" />

    <!-- Sweet Alert-->
    <link href="~/assets/libs/sweetalert2/sweetalert2.min.css" rel="stylesheet" type="text/css" />
    <!-- DataTables -->
    <link href="~/assets/libs/datatables.net-bs4/css/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/libs/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />


    <link href="~/assets/libs/magnific-popup/magnific-popup.css" rel="stylesheet" type="text/css" />
    @await RenderSectionAsync("Styles", required: false)
</head>


<body>

    <!-- <body data-layout="horizontal" data-topbar="colored"> -->
    <!-- Begin page -->
    <div id="layout-wrapper">


        <header id="page-topbar">
            <div class="navbar-header">
                <div class="d-flex">
                    <!-- LOGO -->
                    <div class="navbar-brand-box">
                        <a href="index.html" class="logo logo-dark">
                            <span class="logo-sm">
                                <img src="~/assets/images/logo-sm.png" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/assets/images/logo-dark.png" alt="" height="20">
                            </span>
                        </a>

                        <a href="index.html" class="logo logo-light">
                            <span class="logo-sm">
                                <img src="~/assets/images/logo-sm.png" alt="" height="22">
                            </span>
                            <span class="logo-lg">
                                <img src="~/assets/images/logo-light.png" alt="" height="20">
                            </span>
                        </a>
                    </div>

                    <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
                        <i class="fa fa-fw fa-bars"></i>
                    </button>


                </div>

                <div class="d-flex">






                    <div class="dropdown d-none d-lg-inline-block ms-1">
                        <button type="button" class="btn header-item noti-icon waves-effect" data-bs-toggle="fullscreen">
                            <i class="uil-minus-path"></i>
                        </button>
                    </div>



                    <div class="dropdown d-inline-block">
                        <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                                data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="rounded-circle header-profile-user" src="~/assets/images/users/avatar-4.jpg"
                                 alt="Header Avatar">
                            <span class="d-none d-xl-inline-block ms-1 fw-medium font-size-15">Marcus</span>
                            <i class="uil-angle-down d-none d-xl-inline-block font-size-15"></i>
                        </button>
                        <div class="dropdown-menu dropdown-menu-end">
                            <!-- item-->

                            <a class="dropdown-item" href="#"><i class="uil uil-sign-out-alt font-size-18 align-middle me-1 text-muted"></i> <span class="align-middle">Çıkış </span></a>
                        </div>
                    </div>



                </div>
            </div>
        </header>
        <!-- ========== Left Sidebar Start ========== -->
        <div class="vertical-menu">

            <!-- LOGO -->
            <div class="navbar-brand-box">
                <a href="index.html" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="~/assets/images/logo-sm.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="~/assets/images/logo-dark.png" alt="" height="20">
                    </span>
                </a>

                <a href="index.html" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="~/assets/images/logo-sm.png" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="~/assets/images/logo-light.png" alt="" height="20">
                    </span>
                </a>
            </div>

            <button type="button" class="btn btn-sm px-3 font-size-16 header-item waves-effect vertical-menu-btn">
                <i class="fa fa-fw fa-bars"></i>
            </button>

            <div data-simplebar class="sidebar-menu-scroll">

                <!--- Sidemenu -->
                <div id="sidebar-menu">
                    <!-- Left Menu Start -->
                    <ul class="metismenu list-unstyled" id="side-menu">
                        <li class="menu-title">Menu</li>

                        <li>
                            <a asp-action="Index" asp-controller="Dashboard">
                                <i class="uil-home-alt"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="ContactForm">
                                <i class="uil-home-alt"></i>
                                <span>Mesajlar</span>
                            </a>
                        </li>
                        <li>
                            <a asp-action="Index" asp-controller="Service">
                                <i class="uil-home-alt"></i>
                                <span>Hizmetlerimiz</span>
                            </a>
                        </li>




                    </ul>
                </div>
                <!-- Sidebar -->
            </div>
        </div>
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="container-fluid">

                    @RenderBody()

                    
                    <!-- End d-lg-flex  -->

                </div> <!-- container-fluid -->
            </div>
            <!-- End Page-content -->


            <footer class="footer">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <script>document.write(new Date().getFullYear())</script> © Minible.
                        </div>
                        <div class="col-sm-6">
                            <div class="text-sm-end d-none d-sm-block">
                                Crafted with <i class="mdi mdi-heart text-danger"></i> by <a href="https://themesbrand.com/" target="_blank" class="text-reset">Themesbrand</a>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
        <!-- end main content-->

    </div>
    <!-- END layout-wrapper -->
    <!-- JAVASCRIPT -->
    <script src="~/assets/libs/jquery/jquery.min.js"></script>
    <script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assets/libs/metismenu/metisMenu.min.js"></script>
    <script src="~/assets/libs/simplebar/simplebar.min.js"></script>
    <script src="~/assets/libs/node-waves/waves.min.js"></script>
    <script src="~/assets/libs/waypoints/lib/jquery.waypoints.min.js"></script>
    <script src="~/assets/libs/jquery.counterup/jquery.counterup.min.js"></script>



    <!-- Required datatable js -->
    <script src="~/assets/libs/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/assets/libs/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>

    <!-- Sweet Alerts js -->
    <script src="~/assets/libs/sweetalert2/sweetalert2.min.js"></script>

    <!-- Parsley js -->
    <script src="~/assets/libs/parsleyjs/parsley.min.js"></script>

    <script src="~/assets/libs/magnific-popup/jquery.magnific-popup.min.js"></script>

    <!-- App js -->
    <script src="~/assets/js/app.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SfdEnerji.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SfdEnerji.web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SfdEnerji.web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SfdEnerji.web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">Panel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SfdEnerji.web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>